[build]
  Command = "npm i && npm run build && npm run build:lambda && cp -r node_modules lambda"
  Functions = "lambda"
  Publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
